# Generated by Django 4.1.3 on 2022-11-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
