# Generated by Django 4.1.3 on 2022-12-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_game_created_at_game_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
    ]
