# Generated by Django 4.1.3 on 2022-12-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
