# Generated by Django 4.1.3 on 2022-12-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='profile',
            field=models.ManyToManyField(to='shop.profile'),
        ),
    ]
